import {
  pgTable,
  text,
  timestamp,
  bigint,
  jsonb,
  boolean,
  integer,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

export const sahibindenListe = pgTable("sahibinden_liste", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  baslik: text("baslik"),
  link: text("link"),
  fiyat: bigint("fiyat", { mode: "number" }),
  konum: text("konum"),
  tarih: text("tarih"),
  resim: text("resim"),
  category: text("category"),
  transaction: text("transaction"),
  crawledAt: timestamp("crawled_at").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  koordinatlar: jsonb("koordinatlar").$type<{ lat: string; lng: string }>(),
  satici: text("satici"),
  ilanNo: text("ilan_no"),
  m2: text("m2"),
  resimSayisi: integer("resim_sayisi"),
  detayHatasi: text("detay_hatasi"),
  detayCekildi: boolean("detay_cekildi").default(false),
  detayTarihi: timestamp("detay_tarihi"),
  aciklama: text("aciklama"),
  ozellikler: jsonb("ozellikler"),
  ekOzellikler: jsonb("ek_ozellikler"),
  icOzellikler: jsonb("ic_ozellikler"),
  disOzellikler: jsonb("dis_ozellikler"),
  konumOzellikleri: jsonb("konum_ozellikleri"),
  cephe: text("cephe"),
  resimler: jsonb("resimler").$type<string[]>(),
});

export const miningJobs = pgTable("mining_jobs", {
  id: uuid("id").primaryKey(),
  jobId: text("job_id"),
  category: text("category"),
  transaction: text("transaction"),
  status: text("status"),
  totalPages: integer("total_pages"),
  processedPages: integer("processed_pages"),
  totalListings: integer("total_listings"),
  newListings: integer("new_listings"),
  updatedListings: integer("updated_listings"),
  removedListings: integer("removed_listings"),
  duplicates: integer("duplicates"),
  startedAt: timestamp("started_at"),
  completedAt: timestamp("completed_at"),
  jobType: text("job_type"),
  errorMessage: text("error_message"),
  config: jsonb("config"),
  stats: jsonb("stats"),
  progress: jsonb("progress"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const newListings = pgTable("new_listings", {
  id: uuid("id").defaultRandom().primaryKey(),
  listingId: bigint("listing_id", { mode: "number" }).notNull(),
  baslik: text("baslik"),
  link: text("link"),
  fiyat: bigint("fiyat", { mode: "number" }),
  konum: text("konum"),
  category: text("category"),
  transaction: text("transaction"),
  resim: text("resim"),
  firstSeenAt: timestamp("first_seen_at").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const removedListings = pgTable("removed_listings", {
  id: uuid("id").defaultRandom().primaryKey(),
  listingId: bigint("listing_id", { mode: "number" }).notNull(),
  baslik: text("baslik"),
  link: text("link"),
  fiyat: bigint("fiyat", { mode: "number" }),
  konum: text("konum"),
  category: text("category"),
  transaction: text("transaction"),
  resim: text("resim"),
  lastSeenAt: timestamp("last_seen_at"),
  removedAt: timestamp("removed_at").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  removalReason: text("removal_reason"),
  daysActive: integer("days_active"),
  priceChanges: integer("price_changes").default(0),
  notes: text("notes"),
});

export const miningLogs = pgTable("mining_logs", {
  id: uuid("id").defaultRandom().primaryKey(),
  jobId: uuid("job_id").references(() => miningJobs.id),
  level: text("level"),
  message: text("message"),
  data: jsonb("data"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const categoryStats = pgTable("category_stats", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  category: text("category"),
  transaction: text("transaction"),
  sahibindenCount: integer("sahibinden_count"),
  databaseCount: integer("database_count"),
  diff: integer("diff"),
  status: text("status"),
  lastCheckedAt: timestamp("last_checked_at").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
